nelmio_api_doc:
    documentation:
        info:
            title: customizer.site
            description: This is an awesome app!
            version: v1
    areas:
        path_patterns:
            - ^/api(?!/doc$)