nelmio_api_doc:
    documentation:
        info:
            title: customizer.site
            description: This is an awesome app!
            version: v1
        components:
            securitySchemes:
                BearerAuth:
                    type: http
                    scheme: bearer
    areas:
        path_patterns:
            - ^/api(?!/doc$)