controllers:
    resource:
        path: ../src/Controller/Controller
        namespace: App\Controller\Controller
    type: attribute
api:
    resource:
        path: ../src/Controller/Api
        namespace: App\Controller\Api
    type: attribute

api_controllers:
    resource:
        path: ../src/Controller/ApiController/
        namespace: App\Controller\ApiController
    type: attribute
    prefix: /api/v1

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
