services:
  php:
    image: ghcr.io/eventpoints/customizer.site-php:main
    volumes:
      - php_socket:/var/run/php
      - ./php/php.ini:/usr/local/etc/php/php.ini
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
      test: 50s
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      MERCURE_PUBLIC_URL: "https://customizer.site/.well-known/mercure"
      DATABASE_URL: "postgresql://__CUSTOMIZER_POSTGRES_USER__:__CUSTOMIZER_POSTGRES_PASSWORD__@database:5432/__CUSTOMIZER_POSTGRES_DBNAME__?serverVersion=17&charset=utf8"
      MERCURE_JWT_SECRET: "__CUSTOMIZER_MERCURE_JWT_SECRET__"
      APP_SECRET: "__CUSTOMIZER_APP_SECRET__"
      MAILER_DSN: "__CUSTOMIZER_MAILER_DSN__"
      MESSENGER_TRANSPORT_DSN: "__CUSTOMIZER_MESSENGER_TRANSPORT_DSN__"
      APP_TIMEZONE: "__CUSTOMIZER_APP_TIMEZONE__"
      CORS_ALLOW_ORIGIN: __CUSTOMIZER_CORS_ALLOW_ORIGIN__
    networks:
      - internal

  caddy:
    image: ghcr.io/eventpoints/customizer.site-caddy:main
    depends_on:
      - php
    restart: unless-stopped
    environment:
      SERVER_NAME: ":80"
      MERCURE_PUBLISHER_JWT_KEY: "__CUSTOMIZER_MERCURE_JWT_SECRET__"
      MERCURE_SUBSCRIBER_JWT_KEY: "__CUSTOMIZER_MERCURE_JWT_SECRET__"
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.customizer.rule=Host(`customizer.site`, `www.customizer.site`)"
      - "traefik.http.routers.customizer.tls=true"
      - "traefik.http.routers.customizer.tls.certresolver=le"
    networks:
      - traefik
      - internal

  database:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: "__CUSTOMIZER_POSTGRES_DBNAME__"
      POSTGRES_PASSWORD: "__CUSTOMIZER_POSTGRES_PASSWORD__"
      POSTGRES_USER: "__CUSTOMIZER_POSTGRES_USER__"
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
    networks:
      - internal

  adminer:
    image: adminer:4.8.0
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: database
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.customizer-adminer.rule=Host(`adminer.customizer.io`)"
      - "traefik.http.routers.customizer-adminer.tls=true"
      - "traefik.http.routers.customizer-adminer.tls.certresolver=le"
    networks:
      - internal
      - traefik

networks:
  traefik:
    external: true
  internal:
    external: false

volumes:
  php_socket:
  caddy_data:
  caddy_config: